### ISSUE TITLE
Is there a way to revalidate the blockchain without redownloading it?

### ISSUE THREAD

**Issue by amanusk** [btcsuite/btcd#1132]
Is there a way to perform a re-validation of the blockchain without a complete removal and download? Similar to `--reindex` and/or `--reindex-chainstate` in the reference client? 

Maybe by deleting some file?

Thanks

**Comment by stevenroose** [comment]
What scenario do you have in mind for this feature?

**Comment by amanusk** [comment]
My understanding is that the reference client has this option for a case that the state was saved incorrectly or somehow got corrupted.  I don't see a reason why this could not happen in this implementation (please correct me if I am wrong). 

(By the way, the state is not saved in some separate directory right? Everything is saved in `blocks_ffldb`, both blocks data and state data?)

So currently this is not possible? Does running `-txindex` validate blocks?

Thanks,

**Comment by stevenroose** [comment]
@amanusk Actually, while working on the [gRPC server](https://github.com/btcsuite/btcd/pull/1075), I noticed there is a `verifychain` RPC method that might do exactly what you want. I haven't ported it to gRPC because I was not sure if it made sense. I mean, calling that method could take a week to complete, which is kinda strange, right?

**Comment by amanusk** [comment]
@stevenroose Thanks for pointing this out. I'll look into it and see if this covers my needs.
