### ISSUE TITLE
replace-by-fee tx

### ISSUE THREAD

**Issue by johynpapin** [btcsuite/btcd#1341]
Hello to all of you,

I noticed that when accepting a transaction in the mempool, we check that this transaction does not double-spend an output.

https://github.com/btcsuite/btcd/blob/67e573d211ace594f1366b4ce9d39726c4b19bd0/mempool/mempool.go#L723

If I understand correctly, BTCD therefore does not allow you to overwrite a transaction with one that has more fees (the replace-by-fee principle).

Thank you in advance for your answers, maybe I didn't quite understand something.

(Maybe a better behavior would be to keep the transaction with the most fees? If so, I can make a pull request to modify this.)

**Comment by totaloutput** [comment]
This means that `btcd` doesn't support BIP-0125 yet, meaning on the network, the full nodes that run `btcd` code won't be able to accept these transactions.
The overall bitcoin network has 90% `bitcoind` nodes, most of them support BIP-0125 (since 0.12 Feb of 2016 I think), so your transaction should still get through most of the time and eventually gets included in the block. Hope this help. @johynpapin

**Comment by johynpapin** [comment]
Thank you very much, it's much clearer.
I didn't know this BIP.
