### ISSUE TITLE
Should I use btcd for a new coin?

### ISSUE THREAD

**Issue by harponsUP** [btcsuite/btcd#1388]
I'm beginning the development of a new coin and trying to decide between the main C++ code-base or a Go alternative. 

On the README the project is described as a "extremely stable beta" and it is 6 years old. Would you say it is on par with the C++ implementation in terms of stability and features? Why?

Thanks for your time.

**Comment by hilbert25** [comment]
I want to develop a new coin based on btcd ,too.Because bitcoin-core based on C++ need a 140GB space harddisk,while my harddisk on server is only 40GB.

**Comment by Roasbeef** [comment]
It's likely easier to dig into and maintain the codebase compared to bitcoind.

**Comment by totaloutput** [comment]
I can share some experience if you are still deciding @harponsUP and @hilbert25 ..
The current btcd is pretty stable, code base is more modularized (compare to bitcoind). and it's much more easier to find other golang developers compare to c++ developers.
The compiling time is much much shorter, this will speed up your development.. the lib and tools are rich (not as rich as c++ but good enough). IDE is available, debugging and memory profiling are easy. 

It does need more memory in runtime compare to c++, but it's more to do with how much you want to buffer in memory vs. disk, so it's a tradeoff of performance vs. memory usage.. 

so it largely depends on what you need from your project.. we picked it because of the exact reason @Roasbeef  mentioned above (much easier to maintain the codebase compare to bitcoind)
