### ISSUE TITLE
Example of NewOutboundPeer doesn't work

### ISSUE THREAD

**Issue by arberiii** [btcsuite/btcd#1464]
Example written here https://godoc.org/github.com/btcsuite/btcd/peer#example-package--NewOutboundPeer doesn't work. The reason why is because self connection is not allowed. The example is also in peer_test package and it works there since when tests are init, function peer.TstAllowSelfConns() is called, which is placed in export_test.go file. I try to call same function in the main example but it cannot find the reference of the function because it is in a _test.go file. In my fork I resolved this issue by moving this function somewhere else.

I suggest to rename the file export_test.go to export.go and call the function in the main example.

**Comment by Rjected** [comment]
Yes, there is a global `allowSelfConns` which is only modified in testing. The issue isn't actually in the `allowSelfConns`, but in `sentNonces`, which is also a global. This example would work if the `sentNonces` cache were moved to the `Peer` struct rather than be a global variable. Moving `sentNonces` would also remove the need for `allowSelfConns`, since that's used just for the example.

**Comment by gtank** [comment]
I've also run into this: I'm trying to use just the peer library (but not the entire node) and would like to be able to generate mock peers. I opened #1481 with a fix.
