### ISSUE TITLE
btcd deviating from btc consensus rule

### ISSUE THREAD

**Issue by discoltk** [btcsuite/btcd#1494]
https://github.com/btcsuite/btcd/blob/037489ef505e1e992d957b83f11dc6e4dcdc7d64/server.go#L458

Why are you enforcing non-consensus rules?    Segwit was not a hard fork.   Its not required.

**Comment by jakesyl** [comment]
@Roasbeef would love to hear your thoughts here

**Comment by Roasbeef** [comment]
The user is confused. We gate connecting to peers _segwit only_ peers based on if the soft fork is activated or not.

**Comment by discoltk** [comment]
No confusion.   This "soft fork" is "opt-in", it is not required for peers to support segwit.

**Comment by Roasbeef** [comment]
We want witness data. Peers that don't support the soft-fork won't give us witness data, nor will they give us complete information for transactions. Also note that this is only for _outbound_ peers. Inbound peers that don't support segwit are free to connect to `btcd` nodes (assuming they listen publicly).

**Comment by discoltk** [comment]
My infrastructure runs non-segwit peers on the outside and uses btcd for indexing on the inside.   I'm not interested in witness data as my application does not accept segwit transactions.

**Comment by Roasbeef** [comment]
> I'm not interested in witness data as my application does not accept segwit transactions. 

If you're interested in fully validating the chain to the highest degree, then you need witness data. 

How are you running "non segwit peers"? So you're running very dated versions of your Bitcoin full node software? Otherwise you're applying a patch to ignore the activation, in which case you can also apply a patch to connect to these notes. 

Also note that if you signal segwit, but then send a peer a block without witness data, it'll fail to validate for them so they may end up banning your nodes.

**Comment by discoltk** [comment]
Is Segwit optional or not?
