### ISSUE TITLE
btcctl addmultisigaddress behaves differently with or without optional parameter

### ISSUE THREAD

**Issue by prabal-banerjee** [btcsuite/btcd#1554]
Using btcctl on simnet and connecting to wallet using RPC. 

`btcctl --simnet --wallet --rpcuser=xxx --rpcpass=xxx addmultisigaddress 2 '["037bc82f4a0160ae4d4a36e83c8d21b405f0f42f58e7ab0f180ff11de1267911d2", "0221968171e30f1f57c2d4d2e4e65b00a7339cfcd27168103075b69f212561d2df"]'`
This works correctly and responds with an address. 

However, this does not work. 
`btcctl --simnet --wallet --rpcuser=xxx --rpcpass=xxx addmultisigaddress 2 '["037bc82f4a0160ae4d4a36e83c8d21b405f0f42f58e7ab0f180ff11de1267911d2", "0221968171e30f1f57c2d4d2e4e65b00a7339cfcd27168103075b69f212561d2df"]' "multi"`

Error: -4: imported addresses must belong to the imported account

Facing issue when using btcd rpcclient as the account field is no longer optional in the API. It continuously gives the same error.

**Comment by Roasbeef** [comment]
Since you're importing an address, you need to always use the imported account with the way btcwallet is set up. Since this issue was created however, we've revamped the way importing pubkeys works in btcwallet (it can take xpubs now, etc), you'll be able to import public keys or xpubs and use the non-default account label.
