### ISSUE TITLE
Release: 0.21.0-beta

### ISSUE THREAD

**Issue by Rjected** [btcsuite/btcd#1572]
There have been a few significant PRs since 0.20.1-beta, notably #1509, #1502, #1500, and #1467, so it might be time for a small release.
This issue is here to track PRs that we might want to add to a new release, and also gather opinions about having one.
People who's opinions I'd like to get on this:
@jcvernaleo 
@jakesyl 
@torkelrogstad 
and anyone else who is interested.

**Comment by jcvernaleo** [comment]
Sounds to me like a release might be worth while based on that.

Which leaves the question, are there any other PRs we need to squeeze in before doing a release (assuming no one objects to a release).

**Comment by Rjected** [comment]
Looking at stuff that's been reviewed, #1393 and #1410 both seem very simple, and are reviewed. There's also #1556 which you've approved and #1558 which is not too large, take a look if you have time. I'm prioritizing suggesting things that either are not too large or have already been reviewed and are ready (pass travis, aren't outdated or might need a second look). Let me know what you think about these.

**Comment by Rjected** [comment]
Also for the version number, it turns out that #1467 could potentially be breaking/non-backwards-compatible since exported types and function definitions have been changed, meaning it's 0.21.0-beta rather than 0.20.2-beta. [semver.org](https://semver.org) is referenced in [version.go](https://github.com/btcsuite/btcd/tree/master/version.go) and the version number is compatible with the spec, if we stick to this I think we resolve part of #1545.

**Comment by wpaulino** [comment]
https://github.com/btcsuite/btcd/pull/1560 is required to address a bug introduced in https://github.com/btcsuite/btcd/pull/1529.

**Comment by jakesyl** [comment]
I'm actually thinking a more granular release cycle around semver might be a good idea as we play catch up here- would love to hear everyone else's opinions though

**Comment by jcvernaleo** [comment]
@wpaulino #1560 has changes requested by @Roasbeef so he will need to accept the changes (or the explanation) before that one can go in.

**Comment by wpaulino** [comment]
I would also like to suggest https://github.com/btcsuite/btcd/pull/1577 to provide backwards compatibility for applications that depend on `rpcclient` and communicate with `btcd` backends which have not been updated to handle the new `getblock` request format.

**Comment by onyb** [comment]
## Release notes draft

I came up with a draft release notes for **`0.21.0-beta`**, to help with the process. I'm sure we can improve it, so feedback on the wording/style is most welcome.

It seems we have ironed out all the issues discussed above, and the changeset is already large enough for a minor release. 💪 

#### RPC changes:

* The `Verbose` and `VerboseTx` boolean fields in `btcjson.GetBlockCmd` have been replaced with a single integer field called `Verbosity`, to reflect the new `getblock` RPC call parameters introduced in Bitcoin Core 0.15.0.  (#1529)

  The `getblock` RPC server command in btcd has also been updated with this change.
  Backwards compatibility has been maintained in `rpcclient`. (#1577)
* Added an optional `Params` field to `rpcclient.ConnConfig`, to represent the network that the server is running. (#1467)
* Added a new error code `ErrRPCInWarmup` in `btcjson`.  (#1541)
* Updated `btcjson.GetMempoolEntryResult` to reflect the new `getmempoolentry` response in Bitcoin Core 0.19.0.  (#1524)
* Implemented `rpcclient` methods to invoke `estimatesmartfee` and `generatetoaddress` JSON-RPC commands.  (#1500)
* Implemented `rpcclient` method to invoke `getblockstats` JSON-RPC command.  (#1500)
* Parse serialized transaction from `createrawtransaction` JSON-RPC command using both segwit, and legacy format. (#1502)
* Support cookie-based authentication using a new `CookiePath` field in `rpcclient.ConnConfig`.  (#1460)
* Implemented `rpcclient` method to invoke `getchaintxstats` JSON-RPC command.  (#1571)
* Implemented `rpcclient` method to invoke `fundrawtransaction` JSON-RPC command.  (#1553)
* Implemented `rpcclient` method to invoke `getbalances` JSON-RPC command.  (#1595)
* Added a new method `rpcclient.GetTransactionWatchOnly` to support passing the `include_watchonly` argument to `gettransaction` JSON-RPC command.  (#1592)

### btcctl changes:

* Added `-regtest` mode to btcctl. (#1556)

### Misc changes:

* Fixed a bug due to a deadlock in `connmgr`'s dynamic ban scoring.  (#1509)
* Replaced TravisCI with GitHub Actions.  (#1575)
* Improved chain state init efficiency.  (#1580)
* Added `blockchain.NewUtxoEntry()` to directly create entries for `UtxoViewpoint`.  (#1588)
* Switch to a generic LRU implementation in the `peer` package, from decred/dcrd.  (#1599)

**Comment by jcvernaleo** [comment]
Release notes look good to me.  I think we are have enough in to go ahead with a release.  If anyone objects or things something else desperately needs to go in, comment here, but if not, we'll go forward in a few days.

**Comment by onyb** [comment]
I have updated the release notes above with the recent PRs that were merged. I think we should include #1608 too since it updates the docs for #1529 (part of the release).

I also want to suggest cutting a new release for [btcutil](https://github.com/btcsuite/btcutil/), and bumping the version in btcd's `go.mod`. The release process for btcutil is practically non-existent (no release notes, no signed binaries, etc), however, I prepared the release notes for a **`v1.1.0`** [here](https://gist.github.com/onyb/d0c91f1fbe82f46e8223e1eac3d4f5af).

Releasing btcutil will involve creating two tags/releases:
* `v1.1.0`
* `psbt/v1.1.0`

What do you guys think? cc: @jcvernaleo

**Comment by jcvernaleo** [comment]
100% agree on #1608 

Hadn't thought about btcutil but I suspect you are correct there too.  Will check out your release notes there.

**Comment by Roasbeef** [comment]
> The release process for btcutil is practically non-existent (no release
notes, no signed binaries, etc),

There aren't signed binaries as it's a package/library. One PR we should
consider landing before the next btcutil version is tagged (so far we
usually tag one around the same time we release an lnd version), is this
PR: https://github.com/btcsuite/btcutil/pull/178. It'll allow our PSBT lib
to once again be compatible with wallet software that requires the
additional information for verification purposes.

**Comment by wenweih** [comment]
Look the changes has been approved, may I ask is there any plan to release 0.21.0, thanks.

**Comment by jcvernaleo** [comment]
@wenweih yes, 0.21.0 will be released soon.  I was without internet or power for most of last week so that pushed my schedule back a bit but I'm catching up.

**Comment by jcvernaleo** [comment]
See #1620 for version bump for this release.

**Comment by jakesyl** [comment]
I haven't used windows in a few years, but looks like #1023 is still an issue (msi installer). Should probably address that (or drop support) in the release process

**Comment by jcvernaleo** [comment]
I think the release process just generates an exe (at least the way I remember it).  The msi used to be a totally separate process.

**Comment by jcvernaleo** [comment]
Release is done:
https://github.com/btcsuite/btcd/releases/tag/v0.21.0-beta
