### ISSUE TITLE
Add support for PSBT methods to rpcclient.Client

### ISSUE THREAD

**Issue by federicobond** [btcsuite/btcd#1573]
While developing an integration between LND and Bitcoin Core, I had to fork btcd to add support for the `walletcreatefundedpsbt` and `walletprocesspsbt` methods in the RPC client.

I can try to upstream those changes if there is interest in them.

**Note:** this is not about adding support for the PSBT methods in the btcd node, which is a lot more work.

**Comment by Roasbeef** [comment]
> this is not about adding support for the PSBT methods in the btcd node, which is a lot more work.

This isn't possible given that `btcd` doesn't include a wallet. 

Rather than add them to the client, I think all we need here are the JSON messages. These can then be manually fed into the client with a small wrapper. None of these are websockets messages, so it doesn't need all the extra logic for futures in the client.

**Comment by onyb** [comment]
@jcvernaleo Candidate for the [RPC Board.](https://github.com/orgs/btcsuite/projects/1)

**Comment by federicobond** [comment]
Pull request here: https://github.com/btcsuite/btcd/pull/1596
