### ISSUE TITLE
System requirements for running btcd node

### ISSUE THREAD

**Issue by zeroFruit** [btcsuite/btcd#1673]
Hi,
I'm planning to run btcd node on my k8s cluster. Is there any minimum (or recommended) system requirements for CPU and RAM?

**Comment by jakesyl** [comment]
tbh - if you're running in a kubernetes cluster I'd be more worried about disk i/o. One of the things Kubernetes does to help you scale is seperates the disk from the physical machine. The only way I've gotten btcd to stay up to chain-tip under heavy rpc load is by using a local-ssd.

I've done a performance rundown on how NAS affects performance [here](https://github.com/btcsuite/btcd/issues/1339#issuecomment-687644348).

In any case, this is what our btcd utilization looks like for a k8s pod under heavy utilization:

![image](https://user-images.githubusercontent.com/6392429/102273336-2c39f100-3ef0-11eb-8586-508268ec3bb1.png)

You can get away w/ 2vcpu and 8gb of ram. If you have the option - I recommend setting your pod affinity to a machine that supports cpu bursting. It's very useful for this kind of app since it'll burst on new blocks

**Comment by zeroFruit** [comment]
Thanks for the answer. I've already experienced similar problems on Ethereum Geth ([here](https://www.reddit.com/r/ethdev/comments/k1x78o/why_my_geth_full_node_falls_behind_the_block/?utm_source=share&utm_medium=web2x&context=3) is my Reddit post).

local-ssd looks great, but I think the first step to check is minimum system requirements and I couldn't find docs about it. 

Anyway I haven't think about local-ssd as solution for keeping my node up-to-date. Thanks!
