### ISSUE TITLE
rpcclient: signrawtransaction method is deprecated in bitcoin core, but not updated in btcd

### ISSUE THREAD

**Issue by chkim-dev** [btcsuite/btcd#1722]
i modify signrawtransaction method in btcd to use signrawtransactionwithkey. please update it.

**Comment by Roasbeef** [comment]
The new command was added in this PR: https://github.com/btcsuite/btcd/pull/1642 

`btcd` doesn't implement the new command, so we'll still keep it around for the `rpcclient`.

**Comment by Roasbeef** [comment]
@galileo-pkm I think I understood the OP. If you'd like to add a new command for `signrawtransactionwithkey` then we'd review the PR. Generally we stopped keeping up in lock step w/ `bitcoind` since for example: we don't package a wallet within this project, so the commands are never used in line or tested in the project. 
 
If you take a look at the way the RPC client works, it's relatively straight forward to add a new command _externally_: https://github.com/btcsuite/btcd/blob/v0.23.1/rpcclient/examples/customcommand/main.go 

This gives projects everything they need to keep up with the `bitcoind` API changes/breakages they'd like to keep up with.

**Comment by galileo-pkm** [comment]
Thank you, I will take a look at the example provided.

**Comment by galileo-pkm** [comment]
PR submitted: https://github.com/btcsuite/btcd/pull/1885
