### ISSUE TITLE
 go get github.com/btcsuite/btcd/btcec is failing in docker file

### ISSUE THREAD

**Issue by adnanmirza11** [btcsuite/btcd#1803]
go get github.com/btcsuite/btcd/btcec is failing in docker file and returning
 
 # [github.com/decred/dcrd/dcrec/secp256k1](http://github.com/decred/dcrd/dcrec/secp256k1)
/root/go/src/github.com/decred/dcrd/dcrec/secp256k1/loadprecomputed.go:53:22: undefined: io.ReadAll
The command '/bin/sh -c go get [github.com/btcsuite/btcd/btcec](http://github.com/btcsuite/btcd/btcec)' returned a non-zero code: 2
2022-02-04T12:57:19.612779747Z stdout P

![image](https://user-images.githubusercontent.com/99024107/152533521-68a273b4-b99a-41d6-b58e-de451ac59918.png)

**Comment by Roasbeef** [comment]
Which Go version are you using? You'll need to be using at least Go 1.16.

**Comment by adnanmirza11** [comment]
Yes, I;m using the latest. And this was working fine until the repo of btcd was updated few days ago

**Comment by Roasbeef** [comment]
We're working on cleaning up some of the lingering tags in [this PR](https://github.com/btcsuite/btcd/pull/1805). Rather than always attempt to fetch the latest version of the module, you should be attempting to fetch a particular commit/tag instead. This way you can ensure you're fetching the same version, making your docker container more deterministic. 

You can fetch the last tagged release using: `go get -v github.com/btcsuite/btcd/btcec@v0.22.0-beta`. 

FWIW, I'm unable to reproduce that error, instead I get an error due to one of the bogus tags that were pushed.

**Comment by adnanmirza11** [comment]
I will try this way, let's see
