### ISSUE TITLE
DockerHub image non existant

### ISSUE THREAD

**Issue by jsfour** [btcsuite/btcd#1833]
When I try to pull the latest image from dockerhub it fails:

```bash
$ docker pull btcsuite/btcd:latest
Error response from daemon: pull access denied for btcsuite/btcd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

The btcsuite user does nott seem to exist on dockerhub:

![Screen Shot 2022-03-22 at 4 14 40 PM](https://user-images.githubusercontent.com/1569744/159591543-09b87e40-4c77-4720-85f7-fa54b4b29933.png)

**Comment by rasodu** [comment]
Having the same issue. Is there a change in image name?

**Comment by rasodu** [comment]
@vpereira01 , Can you help? Documentation may be outdated.

**Comment by vpereira01** [comment]
Yes, the docs are outdated. You can build your own docker image with the Dockerfile in the repository.

There hasn't been an official docker image from sometime now but I don't know when/how it stopped being built. 
I have made a PR to build docker images for GitHub registry, instead of DockerHub, but the workflow has not been triggered yet.

The repository collaborators could run manually from the latest release tag but I don't have access.

**Comment by jcvernaleo** [comment]
@vpereira01 I don't recall what happened with the original docker builds.

Anyway, I can manually trigger the workflow if that would be helpful.  But does it make sense to do it from a non-tagged point in the repo?  Or should it wait for a tag?

**Comment by vpereira01** [comment]
I think it's makes more sense to run it for a previous release tag.

Something like this (image from other repo)
![image](https://user-images.githubusercontent.com/42812459/169057551-f1b81c16-23e0-49fa-99ba-7799f1d027c2.png)

**Comment by jcvernaleo** [comment]
Sounds to me waiting for next tag is the best solution here (or building locally if it is something you need).

I'd really like to do a new tag/release sooner rather than later.
