### ISSUE TITLE
btcctl command help: decoderawtransaction misnamed

### ISSUE THREAD

**Issue by T909** [btcsuite/btcd#305]
This not a big deal but from ./btcctl
`
Usage:
  btcctl [OPTIONS]
...
Commands:
...
	debuglevel <levelspec>
	decoderawtransaction <txhash>
	decodescript <hex>
`
It should be` decoderawtransaction <hex>`, not `decoderawtransaction <txhash>`

**Comment by davecgh** [comment]
Thanks for the report.  There is a rewrite of btcctl on a separate branch which will be going in within the next few days that gets rid of the need to manually specify this information (it determines it via reflection), so it will be indirectly fixed by it.

However, I'll leave this open until that is pushed and verify it is indeed fixed with the new code before closing this.
