### ISSUE TITLE
package v2/btcjson only dependencies are core Go packages

### ISSUE THREAD

**Issue by stormasm** [btcsuite/btcd#401]
package v2/btcjson
has no dependencies on btcd or any other packages except in ONE place
and that is here...

func NewOutPointFromWire(op *wire.OutPoint) *OutPoint {
and this function currently is not being used by anyone

so if you wanted to have v2/btcjson only depend on Go's core packages

you could remove that reference and then everyone could use it going forward without needing to use anything but the core go packages

**Comment by jrick** [comment]
`NewOutPointFromWire` is used by `btcrpcclient`.

https://github.com/btcsuite/btcrpcclient/blob/05f1d6c89afb353ce0c6c42dfc0f74dac7e6cd52/notify.go#L758

https://github.com/btcsuite/btcrpcclient/blob/05f1d6c89afb353ce0c6c42dfc0f74dac7e6cd52/notify.go#L973

https://github.com/btcsuite/btcrpcclient/blob/05f1d6c89afb353ce0c6c42dfc0f74dac7e6cd52/notify.go#L1053

We could move this to btcrpcclient since it operates on only exported fields of each type.

**Comment by davecgh** [comment]
I'm fine with this.  It's always good to reduce dependencies.

**Comment by davecgh** [comment]
Doing this now.  I'll update btcrpcclient accordingly as well.
