### ISSUE TITLE
maxOutboundPeers should be configurable

### ISSUE THREAD

**Issue by jameshilliard** [btcsuite/btcd#434]
[This](https://github.com/btcsuite/btcd/blob/master/server.go#L666) value is arbitrary and should be configurable in the same way [maxpeers](https://github.com/btcsuite/btcd/blob/master/doc.go#L35) is.
Maybe use a config flag such as --maxoutboundpeers.

**Comment by davecgh** [comment]
Might I ask what your trying to achieve by raising the limit?

I really don't have a huge issue with having an option for it, but if it were to be added, it should be limited between 2 and 8 as opposed to being limited by `maxpeers`.  The reason for this is that having more than 8 outbound peers does not generally have the effect you might expect (most assume it will improve throughput in some way).  Unfortunately, more outbound connections generally has the opposite effect.  It takes more memory and CPU to maintain those extra peers since each peer maintains various lists such as known inventory, send and receive queues, etc.  Thus, increasing the number of outbound peers can actually lead to poorer performance overall.

Also, while there is currently work underway to support concurrent downloading from multiple peers, currently there is only a single sync peer, so increasing the number of connections doesn't allow you to download the data any faster.  Once the code to download concurrently is finished, we'll re-evaluate if the current value continues to make sense, but there is a very high chance everything is still going to be highly dominated by I/O due to the time it takes to insert the data and necessary updates (utxo set, txidx, addridx if enabled, etc). Thus, it is highly likely that downloading from more peers would simply push more data into memory while it's waiting to be written to disk.

All of the above is in reference to the initial block download.  Once you are synced, having more outbound nodes still doesn't provide any advantages and, in the end, is worse for the network as a whole.  It is more beneficial to the network to provide inbound connections since things such as SPV wallets and the like all need access.  If all of the full nodes bumped up their outbound connections (thus effectively taking away inbound connections since `available = max - outbound`) they'd just be creating more connections to one another.  This in turn would take away resources from nodes and services that need it more.

**Comment by jameshilliard** [comment]
I'm actually less concerned with downloading blocks as I am with uploading blocks for pool servers etc. One possible situation could be a pool server on a mining farm site that is NAT restricted for various reasons beyond their control. Without being able to increase the outbound connection limit that pool server couldn't establish more than 8 connections. In addition it is very hard to get close to 125 inbound connections even when a node is not NAT restricted. Can btcd upload to multiple peers at the same time?

**Comment by dajohi** [comment]
@jameshilliard Yes, btcd can upload to multiple peers at the same time.

**Comment by dajohi** [comment]
@jameshilliard Can you explain why the pool server needs more than 8 connections?

**Comment by jameshilliard** [comment]
To speed up the initial broadcast when blocks are found, pool servers typically run from datacenter grade connections with faster than normal upload speeds so it can be desirable in certain cases to use more than 8 connections to reduce orphans.

**Comment by dajohi** [comment]
@jameshilliard can you run with https://github.com/btcsuite/btcd/pull/441 to see if that fits your needs?

**Comment by jameshilliard** [comment]
That looks like it should work, I'll try and get a test server set up.

**Comment by dajohi** [comment]
@jameshilliard any update?

**Comment by jameshilliard** [comment]
haven't had time to check yet

**Comment by dajohi** [comment]
@jameshilliard any time to test yet?

**Comment by jameshilliard** [comment]
Finally got around to trying to build it, getting this error when I try "go build":
./rpcwebsocket.go:415: not enough arguments in call to btcjson.NewBlockConnectedNtfn
./rpcwebsocket.go:439: not enough arguments in call to btcjson.NewBlockDisconnectedNtfn

**Comment by dajohi** [comment]
run this first:
`
go get -v -u github.com/btcsuite/btcd/...
`

**Comment by jameshilliard** [comment]
I did that but it didn't seem to have the maxoutboundpeers option so I tried cloning https://github.com/dajohi/btcd/tree/maxoutbound and running "go build"

**Comment by dajohi** [comment]
I just rebased.  Try again with the branch.

**Comment by jameshilliard** [comment]
is the are equivalent to "bitcoin-cli getinfo" in btcd?

**Comment by dajohi** [comment]
Yup.

`$ btcctl getinfo`

{
  "version": 110100,
  "protocolversion": 70002,
  "blocks": 365457,
  "timeoffset": -1,
  "connections": 7,
  "proxy": "",
  "difficulty": 5.1076366303481926e+10,
  "testnet": false,
  "relayfee": 1e-05
}

**Comment by davecgh** [comment]
I'm closing this as there does not seem be sufficient interest nor consensus on providing an option by default for it.  As discussed previously often increasing this value leads to poorer performance and also has the issue of saturating full node connection slots with no increased benefits.

That said, PR #441 now exists, so users with specialized needs can apply it to their own forks if they desire.
