### ISSUE TITLE
btcd doesn't connect to client behind NAT that have port forwarding enabled

### ISSUE THREAD

**Issue by ishbir** [btcsuite/btcd#435]
In https://github.com/btcsuite/btcd/blob/master/peer.go#L371, I see that an address is added to addrmgr only if the advertised address and the actual address match. This approach works good for clients behind NAT.

However, if the router has port forwarding enabled, outbound connections can reach the peer but the peer does not have any knowledge of its IP on internet and still gives its local address (i.e. there's a mismatch between advertised and actual addresses). Other nodes, therefore, will be unable to connect to this peer even though it is accessible.

A fix is to remove this check and ensure that the actual address is always added for inbound connections. If connections are unsuccessful, it will be marked as bad by addrmgr anyway.

**Comment by davecgh** [comment]
There is an option [externalip](https://github.com/btcsuite/btcd/blob/master/config.go#L90) to address this.

**Comment by ishbir** [comment]
My bad. I should have looked harder.

**Comment by davecgh** [comment]
I should also mention that I think it would be a good idea at some point to make this a little more automatic by basing it on what other peers report our address as.

There are some important considerations to be made with that approach however since the reported address can't be fully trusted.  Aside from the malicious cases,  the address could be incorrect due to other reasons such as buggy implementations and crawlers that didn't bother to implement it.

**Comment by ishbir** [comment]
I don't think it's wise to ever trust information about ourselves that remote peers tell us.

Do you think that the efficiency loss if btcd simply refused to acknowledge the advertised address of remote peers and just tried to connect to the actual addresses of all peers be noticeable? What problems do you see with this approach other than efficiency? I'm curious why this wasn't used as the default approach, keeping in mind that buggy implementations that aren't aware of their IP exist.
