### ISSUE TITLE
Option for automatically updating btcd

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#480]
It would be useful to have an option for btcd to update itself from GitHub. I believe a lot of people just want to deploy a Bitcoin node and don't want to have to update it every now and then.

I'm not saying btcd should do so by default, but having the options would be nice.

I found this Go package that can easily make an app update itself from GitHub: 
https://github.com/sanbornm/go-selfupdate

**Comment by davecgh** [comment]
I certainly understand the desire for such functionality, however I think it's an extremely dangerous thing for full-node Bitcoin software (whether it be btcd, Core, Toshi, etc) to have due to their very nature.

The problem at heart is that full-nodes are a very different beast from typical software.  Virtually everything that makes Bitcoin worthwhile is precisely because it is decentralized and self-governing.  Allowing its rules to effectively be changed at the press of a button destroys its desirable properties.  Automatic updates essentially provide exactly that button, and perhaps even more alarmingly, they also provide a centralized attack vector.  

To understand why this is the case, imagine a scenario with widespread auto updates on nodes that comprise the majority of the network.  Imagine an attacker gains control of the update mechanism.  They might gain control through hacking, by simply coercing whoever controls it through any number of malevolent actions one can imagine.  In any case, all said attacker has to do now is change a fundamental rule (it doesn't even have to be obviously malicious), push the "send update" button and within minutes the majority of the network is now running rules that could completely destroy it.

I realize your suggestion is to not make it the default and only provide an option.  However, that, in my opinion, would ultimately lead to the same situation since people, understandably, tend towards "set it and forget it".

I would much rather see something like a tool that helps simplify the update process and, more importantly, verifies signatures.

**Comment by jcvernaleo** [comment]
I agree with @davecgh on this one.  Easier updates are a definite goal, but automatic updates are a bit too dangerous in this situation (personally there are very few cases where I don't think auto-updates are dangerous).

**Comment by stevenroose** [comment]
Hmm, I very much understand the issue with automated updates. It would indeed be less dangerous if you could set something up to only accept updates signed by people you trust.

Something in the good direction might be a notification by email whenever a new version of the protocol comes out that btcd has implemented; together with an easy way of effectively updating after having reviewed the changes.

I know about the commits mailing list, but that's a little too much noise for someone that just wants to run the latest Bitcoin protocol version.
