### ISSUE TITLE
BlockManager stops syncing during initial sync

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#486]
I recently deployed btcd to a server with discoverability in order.

I noticed on getaddr.nodelist.io that the block height was no longer increasing (it was still catching up with the network), and this is what I found in the log:
https://gist.github.com/stevenroose/ce3003b8b61b86de5d11

Before that, it was processing blocks as normal, and suddenly it stops. After this excerpt are numerous lines of new connections and lost connections, mostly from `bitcoin-seeder` and `getaddr.bitnodes.io`.

**Comment by davecgh** [comment]
Thanks for the report.  This is a known issue during IBD which is the result of having a single sync peer.  There have somewhat recently been an influx of peers which don't properly serve the chain and unfortunately when the selected sync peer doesn't serve the blocks, there is currently no code to notice this, so it essentially sits there idle waiting for blocks which never come.  Note that this only applies during the initial sync.  Once you're synced, it isn't a problem since the blocks are requested from multiple peers as needed.  Unfortunately, there isn't much you can do at the moment short of disconnecting the peer via btcctl or stopping/restarting btcd.

The current top priority item being working toward is multi-peer downloads which will fix this (and a few other similar type of things) as a part of it.

**Comment by stevenroose** [comment]
Ok, good that you are aware of this. Will restart then.

**Comment by aquarat** [comment]
I've also noticed this issue.

**Comment by stevenroose** [comment]
This really bugs me. btcd stalls more than once a day and I have to restart it manually all the time.
