### ISSUE TITLE
Websocket RPCs should not be processed synchronously.

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#504]
The current websocket RPC server will block both the read and servicing of all later requests until the current request is finished being processed and the response is sent.  While not inherently wrong, this is less useful because two individual requests are not guaranteed to be processed in order, and doing so will cause short requests (e.g. session) that do not depend on database state to block on previous requests that do make database calls.

Before fixing this, we will probably want to consider throttling db calls per websocket client, to avoid issues where one client connects and starts hundreds of db calls which will significantly slow down block processing and other clients.

**Comment by toddfries** [comment]
throttlepeer=* 10
throttlepeer=::1 1024
...

**Comment by davecgh** [comment]
As mentioned on IRC, this is a good idea and something we should do, however we should wait until #380, #491, and #492 are merged since those have a significant impact on this.  In particular all of the RPC calls are converted in those PRs to use MVCC snapshots from the database and the chain state (which the new db and updated concurrent blockchain support).

Those changes mean the vast majority of the current work to ensure concurrency safety that would need to be done to implement this issue is already done.  Also, they provide a rather massive improvement in how quickly the RPC server responds when btcd is under heavy load such as during IBD.

**Comment by jrick** [comment]
I would like to tackle this one soon since all of the prerequisites are completed.
