### ISSUE TITLE
No miningaddr

### ISSUE THREAD

**Issue by mathiasrw** [btcsuite/btcd#532]
If one does not change the configuration to include `miningaddr` will the btcd still mine for at solution to the last broardcasted block? 

if so - when a hash for the last block that fits the puzzle is found - where will the mining reward go?

**Comment by davecgh** [comment]
No, btcd does not mine by default because mining using the CPU on mainnet is a complete waste of effort now (and has been for quite some time) due to the massive hashing power provided by all the ASICs out there.  The probability of finding a block with CPU mining now is so astronomically small that it is effectively impossible.

Mining profitably on mainnet these days is quite a tricky proposition and requires a fair amount of research, investment in specialized hardware, etc.

The main reason btcd even provides CPU mining is for application developers who want to perform testing using its private simulation network capabilities (simnet difficulty is extremely low, and it's private to each person/entity, so it's trivial to mine).

That said, to more directly answer your question, attempting to enable mining without a mining address will result in btcd failing to start as shown below:

> $ btcd --generate
> loadConfig: the generate flag is set, but there are no mining addresses specified
> Use btcd -h to show usage

**Comment by mathiasrw** [comment]
BAAAAAAMMMM - thank you for a really quick respond and a really good answer.
