### ISSUE TITLE
addblock importing error

### ISSUE THREAD

**Issue by nolith** [btcsuite/btcd#576]
Hello,

I'm moving my bitcoin-core full node to btcd,
I've built a bootstrap.dat from my running node but addblock failed to import it

```
15:36:23 2015-12-05 [INF] Processed 55 blocks in the last 10.77s (11877 transactions, height 257987, 2013-09-14 18:02:06 +0200 CEST)
15:36:30 2015-12-05 [WRN] CHAN: fastAdd set in the side chain case? 000000000000001b425aa98dbf7e412decc92bfbe3dbf570de5e8fc4b91cce73

15:36:30 2015-12-05 [INF] CHAN: FORK: Block 000000000000001b425aa98dbf7e412decc92bfbe3dbf570de5e8fc4b91cce73 forks the chain at height 258009/block 00000000000000062c59ab3fbccc867c3be5043f655644d054e99025c9e6764c, but does not cause a reorganize
15:36:30 2015-12-05 [ERR] import file contains block 000000000000001b425aa98dbf7e412decc92bfbe3dbf570de5e8fc4b91cce73 which does not link to the available block chain
```

This is the offending block: https://blockchain.info/block-index/320382/000000000000001b425aa98dbf7e412decc92bfbe3dbf570de5e8fc4b91cce73

What can I do?

**Comment by davecgh** [comment]
How did you create your bootstrap.dat?

From the looks of the error, you just copied the BC block files into a file called bootstrap.dat.  If so, that will not work because it contains the blocks out of order and on side chains,  The `bootstrap.dat` format requires that it has all blocks in order and ONLY has the main chain blocks.

See the https://github.com/bitcoin/bitcoin/tree/ad57b310bac44a7e470cf66276421f2bbc61b1f0/contrib/linearize tool from the BC project in order to create `bootstrap.dat` properly.

**Comment by nolith** [comment]
Thank you.
I followed a bad advice and created it with ```cat```

Now it works.
