### ISSUE TITLE
[rpcserver] Improve JSON-RPC compatibility

### ISSUE THREAD

**Issue by tb00** [btcsuite/btcd#632]
I was having trouble getting CKPool to work with btcd. I isolated multiple issues and narrowed down the root causes. The pool software builds on the behavior of bitcoind/Core which is not mirrored in btcd:

 - Responding to RPC request without an "id" member
 - Terminating the RPC response with a newline

I made changes to CKPool around how JSON-RPC is handled but then figured making btcd more interoperable in this area could be beneficial for others as it would avoid similar compatibility issues with other software that relies on the behavior of bitcoind's JSON-RPC implementation.

I thoroughly read the JSON-RPC specification (1.0 & 2.0) and performed tests with both Core and btcd before raising this issue. If you agree that mirroring Core behavior is beneficial, I will send a PR.

**Comment by davecgh** [comment]
We do generally strive for compatibility where it makes sense.  To that end, and I don't remember what they are now off the top of my head, but there are some cases with Core uses a sort of in-between JSON-RPC 1.0 and JSON-RPC 2.0 and doesn't conform to either spec perfectly.  We had to avoid using the stdlib jsonrpc package specifically because of that in the name of compatibility.

In the case of the id member, do keep in mind the btcd support JSON-RPC 2.0 notifications (via websockets) which the spec specifically states "A Notification is a Request object without an "id" member."  I'm not sure of the specific cases you're hitting in regards to the id, but I thought that was worth mentioning, because there are cases where the id is intentionally omitted.

I'd certainly appreciate a PR that makes it more compatible, so long as it doesn't break JSON-RPC 2.0 notifications via Websockets of course.

**Comment by davecgh** [comment]
Oh I should also note, if you're in the JSON-RPC code anyways and have any desire to work on it, it would be ideal to address #329 as well.  I believe there are several different mining/pool software implementations which make use of JSON-RPC 2.0 batching.

**Comment by jrick** [comment]
> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

http://www.jsonrpc.org/specification#notification

**Comment by tb00** [comment]
@jrick I believe there is a slight difference between 1.0 and 2.0 of the protocol in this regard. You are referring to the 2.0 spec, but that spec is only applicable if the request has "json-rpc":"2.0" (MUST be exactly "2.0"). If the "json-rpc" member has any value other than "2.0", or is omitted, the specification you cited is not applicable.

JSON-RPC 1.0 (http://json-rpc.org/wiki/specification) is a bit different. It is not as precisely written, and it also defines notifications differently. It contains the following:
 - notifications must have "id" set to null
 - unless the request is a notification it must be replied to with a response

The 1.0 specification does not cover protocol version detection (does not require the presence of "json-rpc" member at all) and also does not cover the case of a missing "id".

Rather than comparing the two specifications, I wanted to draw attention to interoperability issues, where btcd shows different behavior than Core. As @davecgh mentioned, Core does not strictly conform with any of those specifications, which is of course not good, given that Core is still the reference implementation. (A side note: btcd treats a missing "id" the same way as "id":null which also violates JSON-RPC 2.0 http://www.jsonrpc.org/specification#id1).

I hope you do not get this the wrong way. My goal is to stick to the specification as much as possible while still providing interoperability/compatibility. Rather than blindly copying the weird behavior of Core, I am suggesting strict conformance when "json-rpc":"2.0" is present in the request but compatibility / quirks mode when "json-rpc" is completely omitted. This would not break JSON-RPC 2.0 notifications, but it would allow better compatibility. Would something like this be in-line with your strategic directions?
