### ISSUE TITLE
btcd using 60% of memory, bitcoind 4%.

### ISSUE THREAD

**Issue by dan-da** [btcsuite/btcd#649]
This is from top.  Same machine.   48 gigs ram.   Both have been running for weeks.

29797 btcd      20   0 33.157g 0.028t   5176 S  29.2 60.5  78941:49 btcd                                         
 2667 bitcoin   20   0 5047952 1.833g   6128 S   9.9  3.9   5034:52 bitcoind                                     

btcd version 0.11.1-beta

Is there a config option I should be using to limit mem usage somehow?

**Comment by davecgh** [comment]
How many entries do you have in the memory pool?  I suspect that's the issue, but would like to confirm.

**Comment by dan-da** [comment]
$ ./btcctl getmempoolinfo
{
  "size": 73902,
  "bytes": 879551016
}

**Comment by tb00** [comment]
My general experience is that btcd uses less memory than bitcoind. This is my personal experience with my nodes similar in configuration, your mileage may vary of course.

Is there a significant difference between mempoolinfo from your btcd versus bitcoind instances? 

If no, then this response will not be relevant for your case. If yes, maybe they differ in which transactions they accept - maybe the mempool of your btcd holds many low fee transactions which might make their way into blocks very slowly. Many nodes are operated with customized settings controlling which transactions are accepted into the mempool and under which condition they are included in blocks.

Version 0.12.0 of btcd offers the following configuration options which I believe are not present in 0.11.1:
- `limitfreerelay`: rate-limiting free transactions could cut the rate at which your mempool grows
- `minrelaytxfee`: allows setting the minimum transaction fee that will be considered non-zero

These should be compared with similar parameters of your bitcoind and tuned carefully if needed.

**Comment by dan-da** [comment]
Ok, I just upgraded to 0.12.0 and restarted.  I didn't change any config options.    At present it is using 0.3% of memory.   I'll watch what it does.

One thing about this node that could differ from some is that its primary purpose is to provide the searchrawtransactions API, and it receives some heavy calls that return thousands of transactions.

Most likely the issue is/was related to the mempool and not API caching or leak.  I just mention it as a data point.

**Comment by dan-da** [comment]
I just remembered to check up on btcd memory usage.  It's been 18 days.

bitcoind is still using about 5.2% of available ram, btcd has grown to 15.3%.

22381 btcd      20   0 10.518g 7.214g   5668 S  24.5 15.3  10186:45 btcd                                         
 2667 bitcoin   20   0 5770728 2.432g   6340 S  10.6  5.2   9892:40 bitcoind

This is using  0.12.0.  Here are my settings:

<pre>
rpcuser=<hidden>
rpcpass=<hidden>
maxpeers=80
rpclisten=127.0.0.1:38334
listen=127.0.0.1:38333
notls=1

; Build and maintain a full address-based transaction index.
addrindex=1
</pre>

So, pretty much default except addrindex=1.   Does that seem a likely culprit?    Is the addrindex cached?    If so, is there a setting to limit the cache size?

**Comment by davecgh** [comment]
This has been improved by #598.  It will be further improved by mempool limiting which is on the agenda.  I'm going to leave this open until the other PRs which address it have landed.

**Comment by davecgh** [comment]
> So, pretty much default except addrindex=1.   Does that seem a likely culprit?    Is the addrindex cached?    If so, is there a setting to limit the cache size?

@dan-da: There are a few caches, one of which is the signature cache which #598 just went into master to improve its speed and reduce its memory usage.  That one can be controlled by the `--sigcachemaxsize ` option.

However, the real culprit is almost positively going to be the memory pool because it's not limited currently.  As your message above showed, you had close to 74k txns in the mempool.  The `bytes` field is only the size of the serialized transactions themselves.  It doesn't account for the fact having those transactions in the mempool causes a lot of usage due to maps, and since you're running with the address index, it includes index entries for all of those pending transactions, etc.

If you don't need access to the transactions in the mempool for your application, you can try running with the new `--blocksonly` option until the other PRs drop which address limiting.  That will effectively disable the mempool and should keep the memory usage low as a result.

**Comment by dan-da** [comment]
@davecgh  thx.  hmm, good to know I could disable the mempool in a pinch.  For now though it is not a problem, so I can wait until the limiting is in place.

how does the limiting decide which tx to drop?  lowest priority?  oldest?

btw, here is present comparison between btcd and bitcoind on the same machine.  number of tx in the mempool is similar.

-- btcd --
./btcctl getmempoolinfo
{ 
  "size": 58587,
  "bytes": 785577274
}

-- bitcoind --
$ bitcoin-cli getmempoolinfo
{   
    "size" : 55569,
    "bytes" : 803707499
}

btcd is using 18.4% of mem and bitcoind is usind 4.4%.

**Comment by davecgh** [comment]
Do you happen to have `--profile` enabled?

**Comment by dan-da** [comment]
no, I posted my btcd.conf above, and I don't run with any command-line args.

**Comment by davecgh** [comment]
Alright, well if you would add `profile=6061` to your conf the next time you restart, we'll be able to get a detailed profile of the memory usage to help track it down.

**Comment by davecgh** [comment]
As an update, I've made a couple of tweaks locally in regards to some GC tuning params and instrumented it to dump the memory stats every second.  Here are the current results for the last 26 hours split into 10 minute intervals.

![memstats_20160415_gc10_26h](https://cloud.githubusercontent.com/assets/2115102/14580609/28a5ccd2-0398-11e6-872b-2925dead02ea.png)

As can be seen from the graph, the memory usage rose as the various caches filled up and it has been fairly stable around 1.6 GB from the Operating System for the last 9 hours.  The number of entries in the memory pool at the current time are:

```bash
$ btcctl getmempoolinfo
{
  "size": 25556,
  "bytes": 347568262
}
```

I'm going to let it continue to run for a while like this in order to monitor it.

**Comment by dan-da** [comment]
ok, I added the profile=6061 yesterday and restarted.   How do I generate a graph, or anyway, what next?

**Comment by davecgh** [comment]
You won't be able to generate a graph like I have above, but you can go to `http://localhost:6061` in the browser and it will redirect you to the profiling interface and it's also possible to use `go tool pprof` with it to get at a lot more details.  I wouldn't worry about it for now.  Once you get to a point you have high usage, I'll walk you through pulling a profile.

**Comment by davecgh** [comment]
As an update, I've been running this for just under 5 days now with stats collection on and per the graph I'm attaching, it has been stable at just under 3GB for roughly the passed 2 days.  The big jump in memory usage around the 75 hour mark was due to me intentionally pounding the RPC server with a ton of concurrent requests.

```
$ btcctl getmempoolinfo
{
  "size": 50430,
  "bytes": 679778976
}
```

![memstats_20160415_gc10_118h](https://cloud.githubusercontent.com/assets/2115102/14666055/c448d286-069c-11e6-9a58-7d83ae2e6d44.png)

That said, I have spent a lot of time in the profiler and have identified several areas that can be drastically improved to reduce the total number of allocations which will cut down on the runtime overhead pretty significantly.

I'm not sure how long it will be before I can get to them though as I won't be able to get to making those optimizations until after the soft-fork BIPs are complete and a release is done with them.

**Comment by dan-da** [comment]
Here's mine at present.

$ ./btcctl getmempoolinfo
{
  "size": 46612,
  "bytes": 651229673
}

Dave, do you also have addrindex=1 enabled?

**Comment by davecgh** [comment]
Yes, I have both `txindex=1` and `addrindex=1`.  I should also note I'm using master which now has all of the new `blockchain` and `database` code which provides a huge performance boost over the old code.

**Comment by davecgh** [comment]
There are a series of pull requests coming to help reduce the pressure on the garbage collector which makes a large difference on the overall runtime memory consumption.

PR #677, which is one such PR, was just merged.

**Comment by davecgh** [comment]
@dan-da: I believe this is resolved by #678.  However, I would like confirmation before closing the issue.

**Comment by dan-da** [comment]
@davecgh  sorry, I didn't see your comment before.  I just built with latest version from master and it is syncing new ffldb blockchain.  If that goes well and I'm able to serve requests with it, I can keep it running and watch the mem for a few days.    Looking forward to reclaiming some memory!

**Comment by dan-da** [comment]
hmm, I started syncing with ffldb last night around 10pm, now it is 8am and only up to block 274398 (2013-12-11).  I had hoped that with the new code I'd be able to sync in under 24 hours, but now it appears not.

top shows up to 11% wait, 500% CPU usage ( 16 core system ).  dstat shows writes up to 45 Mb/sec with avg  about 17 Mb/sec.   Doesn't seem very loaded to me.  hard disk is 7200 RPM.  Am syncing against local btcd (leveldb) and also mainnet peers.  addrindex is enabled.   Would it be faster to disable addrindex and build it after sync, or other suggestions?

**Comment by dajohi** [comment]
I'd recommend trying without addrindex enabled and NOT syncing against another node on the same machine.

**Comment by dan-da** [comment]
@dajohi thx.  I did that and now the speed has more than doubled.  avg is about 15k tx/sec vs before about 7k.   I think it was mainly the addrindex because overnight it was running without local peer and still had the lower speeds.  I just added the local peer this morning in attempt to speedup.

hmm... I wonder is it possible for the new ffldb to use the addrindex data/files from the older leveldb btcd so I can avoid reindexing?   I doubt it, but hope springs eternal...

**Comment by davecgh** [comment]
It's not possible to use the old database to avoid reindexing.  The formats are wildly different with the new one being much more efficient.

**Comment by dan-da** [comment]
still planning to verify this, but getting new instance up/running with ffldb is taking much longer than expected.  See #716.

**Comment by dan-da** [comment]
ok, the new instance finally synced.  It is now serving requests instead of the old one, so I can watch mem usage under real workload.

immediately after startup, here is mem usage:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
25848 btcd      20   0  972652  63732   8712 S   0.7  0.1   0:59.84 btcd
```

**Comment by dan-da** [comment]
2 days later, mem usage is now at 0.6%.   Seems to be rising more slowly than my old build with leveldb.
0.6  58:57.91 btcd

**Comment by dajohi** [comment]
golang doesn't give memory back to the OS.

**Comment by rickw** [comment]
I've been running latest btcd (currently btcd version 0.12.0-beta) and memory has always increased over time and required a restart to bring it down. I'm also running bitcoinclassic 1.1.0 both indexing, and I have geth on the classic box and it's running 15GiB  RAM and 8GiB swap. The btcd box is maxed out on RAM and 16GiB Swap.

**Comment by dan-da** [comment]
ok, so 16 days later, without any restarts:

```
  755 btcd      35  15  9.845g 6.811g   5156 S   4.0 14.4   8756:05 btcdold                                               
  732 btcd      35  15 3828692 1.937g   5164 S   1.0  4.1   6477:46 btcd                                                  
24740 bitcoin   20   0 3580724 657840   6820 S  21.5  1.3   1454:43 bitcoind 
```

It's using about 3x memory as bitcoind, but 1/3rd as much as btcdold (v 0.12-beta).   Also it is a little unfair because btcd is serving searchRawTransaction requests with address indexing enabled and btcdold and bitcoind are not.

tl'dr.  Seems like a big improvement.

**Comment by rickw** [comment]
I should upgrade, thanks.

**Comment by dan-da** [comment]
@rickw just be aware that upgrade will start a new blockchain download with new flat-file db (ffldb).  It can be very slow if you don't have SSD, so plan accordingly.  See #716.

**Comment by davecgh** [comment]
I'm going to go ahead and close this since it is at least significantly improved.  Thanks for confirming.
