### ISSUE TITLE
Allow getrawtransaction to query transactions with unspent outputs

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#673]
Since implementing the optional transaction index, getrawtransaction is unable to query transactions not in mempool when the transaction index is off (this is the default).  This could be improved to allow transaction lookups from the UTXO set when the transaction index is disabled.  This behavior would also match Core.

**Comment by davecgh** [comment]
I have considered this and I'm not really sure whether it should be implemented or not because it is questionable behavior in the face of pruning and it's also quite slow.  Since the utxo set only, by definition, contains pruned versions of the transaction, in order to do full transaction lookups using it, you effectively have to use it as a proxy in order to find the block the full transaction is in, load the entire block,and then scan the transactions to find the one with the hash in question.  This would clearly not be possible with pruned block data since it simply won't be there.

Also, I don't really think it's should even be necessary for wallets to have access to it since they should already have all of the transactions related to the utxos they control in their local data stores anyways.

**Comment by jrick** [comment]
Good point about pruning.  I didn't consider that, and it would make good case for not supporting this functionality.

**Comment by davecgh** [comment]
I forgot to note that there is a `gettxout` RPC which can be used to load a specific UTXO as well.
