### ISSUE TITLE
Sample config file

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#694]
The sample config file suggests that adding `rpclisten=` to the config file makes it listen to all interfaces ([here](https://github.com/btcsuite/btcd/blob/master/sample-btcd.conf#L179)). Instead, the empty parameter makes it keep the default behavior: listening only to localhost.

**Comment by davecgh** [comment]
Interesting.  I just tested this and I don't see that behavior.  Is anyone else seeing the reported behavior?

Here are my results:

With `rcplisten=` (which tells it to listen on all interfaces with the default port) in the config file, I see:

```
$ btcd
11:20:28 2016-05-08 [INF] RPCS: RPC server listening on [::]:8334
11:20:28 2016-05-08 [INF] RPCS: RPC server listening on 0.0.0.0:8334
```

That is correct since `0.0.0.0` means all interfaces in IPv4 and `[::]` means all interfaces in IPv6.

On the other hand, when I comment out `rpclisten` (which means btcd will go back to listening on localhost host with the default port), I see:

```
$ btcd
11:21:33 2016-05-08 [INF] RPCS: RPC server listening on [::1]:8334
11:21:33 2016-05-08 [INF] RPCS: RPC server listening on 127.0.0.1:8334
```

That is also correct since `127.0.0.1` means localhost in IPv4 and `[::1]` means localhost in IPv6.

**Comment by stevenroose** [comment]
Weird, I seemed to have had one run with `rpclisten=` that gave me
`[::1]:8334`, but that will probably have been my bad then.
