### ISSUE TITLE
building addrindex very slow with ffldb

### ISSUE THREAD

**Issue by dan-da** [btcsuite/btcd#716]
I decided to run with ffldb in order to verify the fix for #649.

It was very slow going syncing the blockchain.  After some days, I disabled addrindex.  It still took something like two weeks total before the blockchain was fully synced.   Now I have re-enabled addrindex and attempting to catch it up.   I'm getting somewhere around 1/2 block indexed per minute.

```
09:51:53 2016-06-27 [INF] INDX: Address index is enabled
09:51:54 2016-06-27 [INF] INDX: Catching up indexes from height 382932 to 418231
09:54:26 2016-06-27 [INF] INDX: Indexed 1 block in the last 2m32.28s (637 transactions, height 382933, 2015-11-10 11:08:09 -0800 PST)
09:57:48 2016-06-27 [INF] INDX: Indexed 1 block in the last 3m22.12s (569 transactions, height 382934, 2015-11-10 11:11:01 -0800 PST)
10:00:08 2016-06-27 [INF] INDX: Indexed 1 block in the last 2m20.13s (2708 transactions, height 382935, 2015-11-10 11:43:21 -0800 PST)
10:03:45 2016-06-27 [INF] INDX: Indexed 1 block in the last 1m29.15s (2096 transactions, height 382937, 2015-11-10 12:07:09 -0800 PST)
10:06:29 2016-06-27 [INF] INDX: Indexed 1 block in the last 2m43.8s (1793 transactions, height 382938, 2015-11-10 12:24:17 -0800 PST)
10:08:47 2016-06-27 [INF] INDX: Indexed 1 block in the last 2m18.35s (1125 transactions, height 382939, 2015-11-10 12:29:10 -0800 PST)
10:11:44 2016-06-27 [INF] INDX: Indexed 1 block in the last 2m56.26s (1477 transactions, height 382940, 2015-11-10 12:39:48 -0800 PST)

```

This doesn't seem right to me.

Hardware:
48 gig ram
16 core
dual 7200 RPM drives in software raid 1 configuration.

sample dstat output:

```
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
  3   0  95   1   0   0|1332k 6418k|   0     0 |2988B 2166B|1886  7279 
  3   1  87   9   0   0|1320k   21M|  23k  250k|   0     0 |4363  9131 
  3   1  88   9   0   0|5316k   25M|  35k  187k|   0     0 |3721  7076 
  3   1  87   9   0   0| 688k   17M|  36k  367k|   0     0 |4677    10k
  2   0  92   6   0   0| 688k  147k|  42k  352k|   0     0 |4037  9506 
  2   0  89   9   0   0|1276k   17M|  52k  439k|   0     0 |3893  6178 
  2   1  84  13   0   0| 904k   16M|  45k  472k|   0     0 |5481  8612 
  1   0  79  20   0   0| 272k 8112k|  31k  623k|   0     0 |3721  4261 
  4   1  84  11   0   0|2036k 8873k|  52k  579k|   0     0 |4361  9741 
  3   1  87   9   0   0|1800k   17M|  58k  583k|   0     0 |4163  7058 
```

top is showing btcd using between 10% and 40% with "wait" hovering between 8 and 10.

```
# uptime
 10:08:03 up 437 days, 23:24, load average: 2.95, 2.76, 2.18
```

I'm not sure if this is a software issue or if there is something I could do to speed things up. ( switching to SSD or faster drives is not presently an option. )

suggestions?

**Comment by dan-da** [comment]
evidence that it is btcd causing the bulk of the load:   here is uptime a couple minutes after stopping btcd.

```
$ uptime
 10:23:17 up 437 days, 23:39, 21 users,  load average: 0.24, 1.57, 2.33
```

and a couple minutes after restarting:

```
$ uptime
 10:26:33 up 437 days, 23:42, 21 users,  load average: 1.42, 1.61, 2.21
```

**Comment by dan-da** [comment]
still crawling along...   2016 yay!

```
20:24:51 2016-06-28 [INF] INDX: Indexed 3 blocks in the last 21.13s (2887 transactions, height 392124, 2016-01-06 21:28:43 -0800 PST)
```

**Comment by dan-da** [comment]
update:  it finally caught up this morning.  total time to sync entire blockchain:  17 days.   :(

10:03:51 2016-07-04 [INF] BMGR: Processed 1 block in the last 5m11.17s (1325 transactions, height 419292, 2016-07-04 10:03:58 -0700 PDT)

**Comment by davecgh** [comment]
It definitely takes a long time to catch up the address index if you didn't have it enabled to begin with.  

The reason is because building the address index requires the all of the inputs (previous outputs) to every transaction that it indexes.  Ordinarily, while doing the initial block download, the specific previous outputs are provided via the relatively small utxoset which is partially cached (these is definitely room for more aggressive caching here as it's currently only done at db level right now which limits its effectiveness) and therefore it is significantly faster because normal validation requires the same information so it is already available at that time.

However, when you are catching up, most of those previous outputs that need to be indexed are now spent and so the utxoset can't be used.  Instead, the code has to load every single referenced transaction in order to get the appropriate output and use it.  As you can imagine, this takes a long time as it's an absurd number of transaction loads (hundreds of millions for the full chain).

So, given that, there are really only two things that can be done to speed it up:

1. Make sure you have the address index enabled from the start of the chain sync to ensure it can use the utxoset as it's built (or restart your chain sync from zero rather than using catchup mode)
2. Use an SSD as it's an incredibly I/O intensive process

**Comment by dan-da** [comment]
@davecgh  thx for the explanation.

I did start the sync with addrindex enabled initially but it was taking unexpectedly long so I asked in the other thread and received advice to disable it, after which the sync speed approx doubled.

This is all documented in the comments starting [here](https://github.com/btcsuite/btcd/issues/649#issuecomment-226798772).

I guess it pretty much boils down to SSD is a requirement now, unless you have a month or so to sync.

I would've hoped it could be made about as fast as a torrent download of equivalent size, but maybe that is asking too much.
