### ISSUE TITLE
Why max user agent length in btcd is different from bitcoin?

### ISSUE THREAD

**Issue by sbwdlihao** [btcsuite/btcd#743]
The MaxUserAgentLen of btcd defined in msgversion.go is 2000 where MAX_SUBVERSION_LENGTH of bitcoin  defined in net.h is 256, why are they different? And if btcd node sends a version message which user agent length greater than 256, other bitcoin nodes will reject the message?

**Comment by davecgh** [comment]
Nice catch!  Originally, back when `wire` was written, the protocol had no max length on it at all, and we wanted to limit it to something sane to prevent malicious actors from sending max block size UAs as an attack vector, so we chose 2000.

It seems that Core silently added a limit of 256 to it via bitcoin/bitcoin#4655 and did not create a BIP or bump the protocol version.  I see there was a comment on the PR which asked if it needed a BIP (twice), but went answered.  Unfortunately, we missed the change while reviewing the large amount of PRs that go through the repo.  In reality, this is a pretty benign change since it doesn't affect legitimate peers at all since none of them have UAs that large.

I'll submit a PR shortly to make them match.
