### ISSUE TITLE
Unable to successfully execute btcd tests.

### ISSUE THREAD

**Issue by jongillham** [btcsuite/btcd#772]
With commit 99165eb using Go version 1.6.2 I always get the following error:

```
$ cd $GOPATH/src/github.com/btcsuite/btcd
$ go test -v
$ unable to setup test chain:  connection timeout

$ cd $GOPATH/src/github.com/btcsuite/btcd/rpctest
$ go test -v
$ unable to setup test chain:  connection timeout
```

I tried increasing [`maxConnRetries` in `rpctest/rpc_harness.go`](https://github.com/btcsuite/btcd/blob/99165eb5580b0cb3af1401a9dd641af867852300/rpctest/rpc_harness.go#L170) as a quick guess to a very high value but still no luck; the command just blocks.

I see tests in all the other packages pass. Any help on what am I doing wrong will be appreciated.

**Comment by davecgh** [comment]
Do you have the `btcd` executable in your path?  The `rpctest` framework relies on being able to launch it, so if the same version it is trying to test is not what is launched, that might be your issue.

**Comment by davecgh** [comment]
I am highly considering gating all of the `rpctest`-based tests behind a feature flag.  That way they would continue to be run on CI builds (PR/merges to master), but won't with the standard `go test`.

The reason is that it appears several people are running into issues with them due to things such as what I mentioned previously, Windows not allowing the random ports to be listened on, conflicting ports, etc.  Essentially, the problem is that being able to programmatically launch a fully-configured `btcd` instance with all of the necessary ports open requires careful additional configuration whereas all of the other tests are stateless.

**Comment by jrick** [comment]
I still think we should be testing the rpc server implementation by calling the method handlers directly, instead of actually making a network connection to a newly-started btcd executable :)

But I like the build tag as a way to selectively enable this test on systems where it should work.

**Comment by davecgh** [comment]
@jrick: I agree for unit testing, but I also think there is a place for integration testing which is what the `rpctest` package is intended to provide.

**Comment by davecgh** [comment]
@jrick: I definitely agree for unit testing, but I also think there is a place for integration testing which is what the `rpctest` package is intended to provide.  It's sort of serving a dual purpose right now though.

**Comment by jongillham** [comment]
@davecgh I see, I must have had a stale `btcd` executable in my path as I rebuilt it and all tests work now.

**Comment by davecgh** [comment]
Great, glad to hear that resolved your issue.  I also merged a PR to feature gate it to alleviate the need for the extra configuration in the normal case.
