### ISSUE TITLE
the freelist in btcsuite/btcd/wire/common.go is not necessary and makes the read/write slower significantly

### ISSUE THREAD

**Issue by rivercheng** [btcsuite/btcd#925]
In  the following code, Go's escape analysis will make sure the buf is allocated on the stack, not on the heap. It's much faster than the original version using freelist.
```
func (l binaryFreeList) Uint8(r io.Reader) (uint8, error) {
    buf := make([]byte, 1)
    if _, err := io.ReadFull(r, buf); err != nil {
        return 0, err
    }
    rv := buf[0]
    return rv, nil
}
```
This version will improve the read/write to be **2 or 3 times faster.**

On my computer: 
**current code (using freelist)**
BenchmarkWriteVarInt1-2         	20000000	        82.7 ns/op
BenchmarkWriteVarInt3-2         	10000000	       177 ns/op
BenchmarkWriteVarInt5-2         	10000000	       177 ns/op
BenchmarkWriteVarInt9-2         	10000000	       183 ns/op
BenchmarkReadVarInt1-2          	20000000	        92.0 ns/op
BenchmarkReadVarInt3-2          	10000000	       198 ns/op
BenchmarkReadVarInt5-2          	10000000	       199 ns/op
BenchmarkReadVarInt9-2          	10000000	       192 ns/op
BenchmarkReadVarStr4-2          	10000000	       156 ns/op
BenchmarkReadVarStr10-2         	10000000	       179 ns/op
BenchmarkWriteVarStr4-2         	10000000	       119 ns/op
BenchmarkWriteVarStr10-2        	10000000	       127 ns/op
BenchmarkReadOutPoint-2         	10000000	       127 ns/op
BenchmarkWriteOutPoint-2        	10000000	       100 ns/op
BenchmarkReadTxOut-2            	 5000000	       301 ns/op
BenchmarkWriteTxOut-2           	10000000	       184 ns/op
BenchmarkReadTxIn-2             	 3000000	       428 ns/op
BenchmarkWriteTxIn-2            	 5000000	       284 ns/op

**After removing freelist and using codes as above.**
BenchmarkWriteVarInt1-2         	100000000	        21.1 ns/op
BenchmarkWriteVarInt3-2         	20000000	        59.5 ns/op
BenchmarkWriteVarInt5-2         	20000000	        60.7 ns/op
BenchmarkWriteVarInt9-2         	20000000	        71.0 ns/op
BenchmarkReadVarInt1-2          	50000000	        34.9 ns/op
BenchmarkReadVarInt3-2          	20000000	        87.1 ns/op
BenchmarkReadVarInt5-2          	20000000	        90.6 ns/op
BenchmarkReadVarInt9-2          	20000000	        92.0 ns/op
BenchmarkReadVarStr4-2          	10000000	       115 ns/op
BenchmarkReadVarStr10-2         	10000000	       116 ns/op
BenchmarkWriteVarStr4-2         	20000000	        62.5 ns/op
BenchmarkWriteVarStr10-2        	20000000	        69.3 ns/op
BenchmarkReadOutPoint-2         	20000000	        72.7 ns/op
BenchmarkWriteOutPoint-2        	30000000	        46.6 ns/op
BenchmarkReadTxOut-2            	10000000	       203 ns/op
BenchmarkWriteTxOut-2           	20000000	        79.0 ns/op
BenchmarkReadTxIn-2             	 5000000	       277 ns/op
BenchmarkWriteTxIn-2            	10000000	       117 ns/op

**Comment by jrick** [comment]
It's faster due to no synchronization (with channels, which are even slower than just using mutexes) with the free list.  The buffer allocation still leaks.

Using Go 1.7.5, and building with `-gcflags='-m'` to see the escape analysis output, on your code I see:

```
.\common.go:75: make([]byte, 1) escapes to heap
```

Why does it escape?  Because the reader is an interface and can do **anything**.  Including this:

```
type evilReader struct {
}

var global []byte

func (r evilReader) Read(p []byte) (int, error) {
	global = p
	return len(p), nil
}
```

This would be wildly unsafe if the buffer was stack allocated because it would be pointing to an object who's lifetime has already ended.  The Go compiler must make a worst case assumption and can never stack allocate that buffer.

Interfaces destroy performance because they prevent the compiler from applying many of its optimizations.

**Comment by davecgh** [comment]
I'm going to close this because it is actually necessary.  As @jrick pointed out, the buffer allocation leaks to the heap because of the interface and there is no way around that in Go.  Your code is indeed faster because it's trading synchronization for GC, however that doesn't consider all of the extra overhead it putting onto the GC.  See #684 for a detailed treatment with graphs of why this is necessary.

**Comment by rivercheng** [comment]
Thanks a lot for the explanation. Now I understand why the freelist is used here.  Maybe a lock free queue can be used here to improve the performance?
