### ISSUE TITLE
Move blockManager into it's own sync package

### ISSUE THREAD

**Issue by jimpo** [btcsuite/btcd#978]
blockManager implements the blockchain syncing protocol in addition to adding/removing transactions from the mempool in response to peer notifications. This is a lot of important logic that in contained in the main package without unit tests.

I propose creating a `sync` package that is responsible for keeping the blockchain and transaction mempool in sync with the peers. It will essentially have the responsibilities of the current block manager, though some logic will be moved around to decouple it from `server`. A primary goal of the refactor is to add more test coverage.

Once this logic is encapsulated in a package, further improvements should be easier such as:
- Headers first syncing (past checkpoints)
- Parallel block downloading
- Accepting BIP 130 direct header announcements
- BIP 152 support

Steps:
- Remove dependency of blockManager on server
- Either remove references in blockManager interface to serverPeer or make public ServerPeer interface
- Move blockmanager.go and blocklogger.go into sync package
- Reify sync package public interface
- Add unit test coverage
- ...
- Profit

**Comment by davecgh** [comment]
So, my first though is that I completely agree that block manager could use a bit of decoupling.  As an aside, the same is true of the rpcserver package (and I have a local branch that has some work done towards that end, but it woefully out of date now).

Something that I have wanted to get to for quite some time now, but just have never had a chance is multi-peer syncing.  That is precisely parallel block downloading, full headers first syncing, BIP130 and BIP152.  It should be noted that it already does do some header-first syncing when before the last checkpoint where it downloads the headers up to the next checkpoint, then the blocks, then the next set of headers up to the next checkpoint, etc.  It would indeed be better to switch over to a full headers first sync where it doesn't rely on checkpoint.

That said, there are quite a few things that need to happen for that to be viable.  Specifically in regards to how the database and blockchain packages handle the block index.  A little more concretely, in order to support parallel block download there needs to be the ability to keep track of different "states" for blocks in the database which is something that does not currently exist.  The database/chain package always assumes that the blocks are connected in order.

I'm definitely on board with the idea.

**Comment by jrick** [comment]
I had the exact same idea of improving the btcwallet code by using sync packages (there would be at least two there, for rpc and spv), so I'm also in favor of this.
